"""empty message

Revision ID: dcee80346a8b
Revises: efd08209818d
Create Date: 2022-10-22 13:38:25.633797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcee80346a8b'
down_revision = 'efd08209818d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('items', sa.Text(), nullable=True))
    op.drop_column('Order', 'item_two')
    op.drop_column('Order', 'item_one')
    op.drop_column('Order', 'item_three')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('item_three', sa.TEXT(), nullable=True))
    op.add_column('Order', sa.Column('item_one', sa.TEXT(), nullable=True))
    op.add_column('Order', sa.Column('item_two', sa.TEXT(), nullable=True))
    op.drop_column('Order', 'items')
    # ### end Alembic commands ###
