"""empty message

Revision ID: efd08209818d
Revises: 3f4b21bec9cf
Create Date: 2022-10-22 13:27:56.410689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd08209818d'
down_revision = '3f4b21bec9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('item_one', sa.Text(), nullable=True))
    op.add_column('Order', sa.Column('item_two', sa.Text(), nullable=True))
    op.add_column('Order', sa.Column('item_three', sa.Text(), nullable=True))
    op.drop_column('Order', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('items', sa.TEXT(), nullable=True))
    op.drop_column('Order', 'item_three')
    op.drop_column('Order', 'item_two')
    op.drop_column('Order', 'item_one')
    # ### end Alembic commands ###
